- name: functions
  hosts: localhost
  connection: local
  vars: 
    colors: yellow, red, blue, pink #these are strings
   
    tags: #this is a dictionary/map with key-pair value
      Application: catalogue  
      Environment: UAT  
   
    listTags: # they have started with - so its a list
    - key: Application
      value: payment
    - key: Environment
      value: dev  
  
  tasks:
  - name: default variables
    ansible.builtin.debug: 
      msg: "hello, {{ name | default('Ramesh') }}" #default is a function

  #converting string to list using split function
  - name: convert string to list
    ansible.builtin.debug:
      msg: "colors are: {{ colors |  split(',') }}"  

  #converting dictionaries to list
  - name: convert map to list
    ansible.builtin.debug:
      msg: "Tags are: {{ tags | dict2items }}"

  #converting list to map
  - name: convert list into map
    ansible.builtin.debug:
      msg: "tag map: {{ listTags | items2dict }}"

  #convert yaml to json.
  - name: read yaml and take it into the variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}" 

  - name: convert yaml to json
    ansible.builtin.debug:
      msg: "json: {{ student_yaml | to_json }}" 

  - name: save json to file    
    ansible.builtin.copy:
      dest: ./student-data.json
      content: "{{ student_yaml | to_nice_json }}"  
      
  - name: convert uppercase
    ansible.builtin.debug:
      msg: "{{ name | upper }}"

  - name: convert lowercase
    ansible.builtin.debug:
      msg: "{{ gmail | lower }}"

  - name: check IP is valid or not
    ansible.builtin.debug: 
      msg: "{{ ipaddress | ansible.utils.ipv4 }}"

  - name: grep for root
    #ansible.builtin.command: cat /etc/passwd | grep root
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: command_output

  - name: print the command_output
    ansible.builtin.debug:
      msg: "{{ command_output }}"

  - name: redirect the output
    ansible.builtin.command: ls -ltr > /tmp/output.txt
    register: redirect_output
    ignore_errors: true

  - name: print redirect_output
    ansible.builtin.debug:
      msg: "{{ redirect_output }}"

  - name: redirect the output using shell
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
    register: redirect_output

  - name: print redirect_output shell
    ansible.builtin.debug:
      msg: "{{ redirect_output }}"
  